[project]
name = "elli-pics"
version = "0.1.0"
description = "Pics of Elliptic Fibrations"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "manim>=0.19.0",
    "numpy>=2.3.3",
    "sympy>=1.14.0",
]
